name: digit_to_word
description: Convert digits to their english word representations. 4235 becomes four thousand two hundred thirty-five, etc.
version: 1.1.0
homepage: https://github.com/kalebhermes/digit_to_word

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.8
